name: wemapgl
description: WeMap Flutter SDK
version: 0.1.0
homepage: https://github.com/WEMAP-Official/WeMap-Flutter-SDK

dependencies:
  flutter:
    sdk: flutter
  wemapgl_platform_interface:
    path: ./wemapgl_platform_interface
    
  fluttertoast: ^8.0.6
  url_launcher: ^6.0.3
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  path_provider: ^2.0.1
  http: ^0.13.2
  async: ^2.5.0
  connectivity: ^3.0.3
  rubber: ^1.0.0
  syncfusion_flutter_charts: ^19.1.58
  google_fonts: ^2.0.0
  weather_icons: ^2.0.2
  cupertino_icons: ^1.0.2
  snaplist: ^0.1.8
  location: ^4.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.wemap.wemapgl
        pluginClass: WeMapMapsPlugin
      ios:
        pluginClass: WeMapMapsPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  # Flutter versions prior to 1.10 did not support the flutter.plugin.platforms map.
#  flutter: ">=1.10.0 <2.0.0"
